services:
    _defaults:
        autowire: true
        autoconfigure: false

    # command bus
    App\Article\Infrastructure\Messenger\MessengerCommandBus:
        arguments:
            $messageBus: '@messenger.bus.command'

    App\Shared\Infrastructure\Bus\CommandBusInterface:
        alias: App\Article\Infrastructure\Messenger\MessengerCommandBus

    # command handler
    App\Article\Application\Command\:
        resource: '%kernel.project_dir%/src/Article/Application/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.command }
