services:
    _defaults:
        autowire: true
        autoconfigure: false
        tags:
            - { name: console.command }

    App\Article\Application\Console\WriteNewArticleConsoleCommand: ~
