version: '3.8'

services:
  php:
    container_name: php
    build:
      context: ./
    volumes:
      - php:/var/www/html:delegated

  mysql:
    container_name: mysql
    image: mysql:5.6.26
    depends_on:
      - php
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/mysql/config/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
      - mysql:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cqrs_es_example
    ports:
      - 3306:3306

  rabbit:
    container_name: rabbit
    image: rabbitmq:3.8.5-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_VHOST: /

volumes:
  php:
    driver: local
    driver_opts:
      type: none
      device: $PWD/app
      o: bind
  mysql:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/mysql/storage
      o: bind
  rabbitmq-data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/rabbitmq/data
      o: bind
