imports:
    - { resource: services/article/commands.yaml }
    - { resource: services/article/console_commands.yaml }
    - { resource: services/article/projectors.yaml }
    - { resource: services/article/queries.yaml }
    - { resource: services/article/repositories.yaml }
    - { resource: services/jphooiveld_event_sauce.yaml }
    - { resource: services/shared/projectors.yaml }
    - { resource: services/user/commands.yaml }
    - { resource: services/user/console_commands.yaml }
    - { resource: services/user/domain_services.yaml }
    - { resource: services/user/projectors.yaml }
    - { resource: services/user/queries.yaml }
    - { resource: services/user/repositories.yaml }
    - { resource: services/user/serializer.yaml }
    - { resource: services/user/translators.yaml }

parameters:
    symfony:
        container_xml_path: '%kernel.project_dir%/var/cache/dev/App_KernelDevDebugContainer.xml'
