imports:
    - { resource: services/commands.yaml }
    - { resource: services/queries.yaml }
    - { resource: services/projectors.yaml }
    - { resource: services/domain_services.yaml }
    - { resource: services/repositories.yaml }
    - { resource: services/console_commands.yaml }
    - { resource: services/translators.yaml }
    - { resource: services/jphooiveld_event_sauce.yaml }
    - { resource: services/serializer.yaml }

parameters:
    symfony:
        container_xml_path: '%kernel.project_dir%/var/cache/dev/App_KernelDevDebugContainer.xml'
