imports:
    - { resource: services/repositories.yaml }
    - { resource: services/console_commands.yaml }

parameters: ~

services:
    _defaults:
        autowire: true
        autoconfigure: false

    # command bus
    App\User\Infrastructure\Messenger\MessengerCommandBus:
        arguments:
            $messageBus: '@messenger.bus.command'

    App\Shared\Infrastructure\Bus\CommandBusInterface:
        alias: App\User\Infrastructure\Messenger\MessengerCommandBus

    # command handler
    App\User\Application\Command\:
        resource: '../src/User/Application/Command/*Handler.php'
        tags:
            - {name: messenger.message_handler, bus: messenger.bus.command }

    # query bus
    App\User\Infrastructure\Messenger\MessengerQueryBus:
        arguments:
            $messageBus: '@messenger.bus.query'

    App\Shared\Infrastructure\Bus\QueryBusInterface:
        alias: App\User\Infrastructure\Messenger\MessengerQueryBus

    # query handler
    App\User\Application\Query\:
        resource: '../src/User/Application/Query/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.query }

    # custom serializer
    App\User\Infrastructure\Messenger\CommandSerializer:
        arguments:
            $serializer: '@messenger.transport.symfony_serializer'

    App\User\Infrastructure\Messenger\CommandSerializerInterface:
        alias: App\User\Infrastructure\Messenger\CommandSerializer
