services:
    _defaults:
        autowire: true
        autoconfigure: false
        tags:
            - { name: console.command }

    App\User\Application\Console\RegisterUserConsoleCommand: ~

    App\User\Application\Console\GetUserByUuidConsoleCommand: ~

    App\User\Application\Console\UpdateUserNameConsoleCommand: ~

    App\User\Application\Console\AddAddressToUserConsoleCommand: ~

    App\User\Application\Console\RemoveAddressFromUserConsoleCommand: ~

    App\User\Application\Console\ExampleScenarioConsoleCommand: ~

    App\User\Application\Console\EmptyTablesConsoleCommand: ~
