services:
    _defaults:
        autowire: true
        autoconfigure: false

    App\User\Infrastructure\Doctrine\Repository\UserRepository: ~

    App\User\Domain\Repository\UserRepositoryInterface:
        alias: App\User\Infrastructure\Doctrine\Repository\UserRepository
