services:
    _defaults:
        autowire: true
        autoconfigure: false

    App\User\Infrastructure\Doctrine\Repository\UserRepository:
        arguments:
            $aggregateRootRepository: '@jphooiveld_eventsauce.aggregate_repository.user'

    App\User\Domain\Repository\UserRepositoryInterface:
        alias: App\User\Infrastructure\Doctrine\Repository\UserRepository
