services:
    _defaults:
        autowire: true
        autoconfigure: false

    App\User\Infrastructure\Doctrine\Repository\UserRepository:
        arguments:
            $userTranslator: '@App\User\Infrastructure\Translator\UserTranslator'

    App\User\Domain\Repository\UserRepositoryInterface:
        alias: App\User\Infrastructure\Doctrine\Repository\UserRepository
