framework:
    messenger:
        default_bus: messenger.bus.command
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json

        transports:
            cqrs_es_example:
                dsn: '%env(resolve:MESSENGER_TRANSPORT_DSN)%'
                options:
                    queues:
                        cqrs_es_example_queue: ~
                serializer: App\User\Infrastructure\Messenger\CommandSerializerInterface

#        routing:
#            App\User\Application\Command\CommandInterface: cqrs_es_example

        buses:
            messenger.bus.events: ~
            messenger.bus.command: ~
            messenger.bus.query: ~
