services:
    _defaults:
        autowire: true
        autoconfigure: false

    App\Shared\Infrastructure\Doctrine\Projector\:
        resource: '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Projector/*Projector.php'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.events }
